# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 20:57
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instacaller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattached',
            name='contacts',
        ),
        migrations.AddField(
            model_name='userattached',
            name='contacts',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
