# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('instacaller', '0002_auto_20190415_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUserDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instacaller.GlobalUserDB')),
            ],
        ),
        migrations.CreateModel(
            name='UserContactDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ManyToManyField(related_name='contacts_list', to='instacaller.GlobalUserDB')),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_user', to='instacaller.RegisteredUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='userattached',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAttached',
        ),
    ]
