# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('instacaller', '0003_auto_20190415_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.AlterField(
            model_name='usercontactdb',
            name='contacts',
            field=models.ManyToManyField(related_name='contacts_list', to='instacaller.UserDB'),
        ),
        migrations.AlterField(
            model_name='usercontactdb',
            name='registered_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_user', to='instacaller.UserDB'),
        ),
        migrations.DeleteModel(
            name='GlobalUserDB',
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
